name: Node CI

on: [push]

jobs:
  questions:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finalExamQuestions

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
      env:
        CI: true

  app:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finalExamApp
      env:
        CI: true
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/finals
        PORT: 3002
    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install &  build
      run: |
        npm i
    - name: create database
      run: |
        node db.js
    - name: run tests
      run: |
        npm test
