name: Node CI

on: [push]

jobs:
  questions:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finalExamQuestions

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
      env:
        CI: true

  app:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: finalExamApp

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm start && npm test
      env:
        CI: true
